export { apiFetch, ApiError } from "./client"
export type { ApiResponse } from "@/src/types/api-response"

export { getTiposPrograma, getTipoProgramaBySlug } from "./endpoints/tipos-programa"
export { getFacultades } from "./endpoints/facultades"
export { getCursos } from "./endpoints/cursos"
export { getProgramas, getProgramaBySlug } from "./endpoints/programas"
export type { ProgramasFilters } from "./endpoints/programas"
export { getProgramasCursos } from "./endpoints/programas-cursos"
export type { ProgramasCursosFilters } from "./endpoints/programas-cursos"
